### ISSUE TITLE
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

### ISSUE THREAD

**Issue by monkpit** [monkpit/monkblog#1]
When the app is being run on a local machine with mysql and pymysql, the database will work for long periods of time.

When the app is hosted, the host has a connection timeout of 5 minutes, and the server throws lots of errors like this:

```
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query') [SQL: 'SELECT posts.id AS posts_id, posts.author_id AS posts_author_id, posts.slug AS posts_slug, posts.title AS posts_title, posts.passphrase AS posts_passphrase, posts.body AS posts_body, posts.pub_date AS posts_pub_date, posts.category_id AS posts_category_id \nFROM posts \nWHERE posts.passphrase IS NULL ORDER BY posts.pub_date DESC \n LIMIT %s'] [parameters: (10,)]
2015-09-22 22:15:13,889 :Exception on / [GET]
Traceback (most recent call last):
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/pymysql/cursors.py", line 134, in execute
    result = self._query(query)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/pymysql/cursors.py", line 282, in _query
    conn.query(q)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/pymysql/connections.py", line 768, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/pymysql/connections.py", line 929, in _read_query_result
    result.read()
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/pymysql/connections.py", line 1125, in read
    first_packet = self.connection._read_packet()
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/pymysql/connections.py", line 882, in _read_packet
    packet_header = self._read_bytes(4)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/pymysql/connections.py", line 909, in _read_bytes
    2013, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/monkpit/mysite/monkblog/blueprints/site_blueprint.py", line 12, in post_index
    post_objects = db.session.query(Post).filter_by(passphrase=None).order_by(Post.pub_date.desc()).limit(10).all()
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2399, in all
    return list(self)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2516, in __iter__
    return self._execute_and_instances(context)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2531, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/pymysql/cursors.py", line 134, in execute
    result = self._query(query)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/pymysql/cursors.py", line 282, in _query
    conn.query(q)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/pymysql/connections.py", line 768, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/pymysql/connections.py", line 929, in _read_query_result
    result.read()
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/pymysql/connections.py", line 1125, in read
    first_packet = self.connection._read_packet()
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/pymysql/connections.py", line 882, in _read_packet
    packet_header = self._read_bytes(4)
  File "/home/monkpit/.virtualenvs/blog/lib/python3.4/site-packages/pymysql/connections.py", line 909, in _read_bytes
    2013, "Lost connection to MySQL server during query")
```

**Comment by monkpit** [comment]
Closed for now, should be fixed with #4
